return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  main = 'nvim-treesitter.configs',
  opts = {
    ensure_installed = {
      'lua',
      'vim',
      'vimdoc',
      'luadoc',
      'html',
      'css',
      'javascript',
      'typescript',
      'tsx',
      'json',
      'jsonc',
      'java',
      'python',
      'yaml',
      'toml',
      'dockerfile',
      'terraform',
      'bash',
      'make',
      'diff',
      'gitignore',
      'regex',
      'cmake',
      'sql',
      'csv',
      'markdown',
      'markdown_inline',
    },
    auto_install = true,
    highlight = { enable = true },
    indent = { enable = true },
  },
}
